### ISSUE TITLE
Is Twitch login not backward compatible with the previous versions?

### ISSUE THREAD

**Issue by Priyankcoder** [authorizerdev/authorizer-react#43]
I have been using authorizer-react package for a month now and recently it started throwing error when I ran npm install
`Error: Cannot query field "is_twitch_login_enabled" on type "Meta". Did you mean "is_twitter_login_enabled", "is_github_login_enabled", "is_google_login_enabled", "is_apple_login_enabled", or "is_facebook_login_enabled"?`. I am using exact version 1.1.13 of authorizer. Ideally, it should not happened.

I checked the package-lock.json file and can see I am using authorizer.js 1.2.18. I reverted the package-lock.json and used npm ci to install the dependencies and it worked. 
Attaching the ss for reference. 

* package-lock.json
<img width="1132" alt="Screenshot 2023-12-07 at 7 36 15 PM" src="https://github.com/authorizerdev/authorizer-react/assets/39910453/f7bbf75a-4a10-454b-83c2-f99f01ade12b">

* React Error
![Screenshot 2023-12-07 at 7 04 07 PM](https://github.com/authorizerdev/authorizer-react/assets/39910453/05686ed4-1d2b-4509-b59c-7e7634429b0d)

**Comment by lakhansamani** [comment]
That is not backwards compatible you will have to update authorizer version

**Comment by Priyankcoder** [comment]
It'll break all the prod apps in the next deployment even if the authorizer version is locked with the exact version. Is there any better way to roll out such a minor feature without breaking the existing one? 
Ideally, If the dependency is locked in package.json then it should not happen.

**Comment by lakhansamani** [comment]
It will not break prod apps as backend is completely backward compatible with db

**Comment by Priyankcoder** [comment]
In my case graphql api is throwing error `Error: Cannot query field "is_twitch_login_enabled" on type "Meta"`. I am running the binary server of 1.1.13 version provided on the website. Let me know if you need more logs regarding this error.

**Comment by lakhansamani** [comment]
Can you update your server to latest version that is 1.3.4

That should solve the problem
